### PR TITLE
Feature/auto change meaning field for FLEx

### PR DESCRIPTION
**Pull request by glasseyes**
For a project that has been created by FLEx

and has just been received from USB, internet or ChorusHub
if there is no .WeSayConfig then project is new from FLEx so automatically set the meaning field to gloss

If the project has already had interaction with WeSay
then the person with FLEx should do the migration manually

for WS-472

3e7503e
@glasseyes
glasseyes
don't ask question but auto change to gloss mf

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/wesay/25)

### CODE REVIEW

**Comment by ddaspit** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/WeSay.ConfigTool/ConfigurationWindow.cs, line 297 at r1](https://reviewable.io:443/reviews/sillsdev/wesay/25#-KynKOgBYfR0j6OvWKe1:-KynKOgBYfR0j6OvWKe2:bpklb1h) ([raw file](https://github.com/sillsdev/wesay/blob/8542e89e1691942b099eada25875c9c6404442e4/src/WeSay.ConfigTool/ConfigurationWindow.cs#L297)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <returns>true if the project was sucessfully opend</returns>
> 		public bool OpenProject(string path, bool newClone)
> ```

I noticed that most of the calls to this method pass "false" to the "newClone" parameter. You might want to consider giving this parameter a default value of "false". It is entirely up to you though. I just wanted to make you aware of the option.

---

*[src/WeSay.Project/WeSayWordsProject.cs, line 284 at r1](https://reviewable.io:443/reviews/sillsdev/wesay/25#-KynJweyw_wxMylkxgc-:-KynJwezTcNTvScG24ET:b-b27z88) ([raw file](https://github.com/sillsdev/wesay/blob/8542e89e1691942b099eada25875c9c6404442e4/src/WeSay.Project/WeSayWordsProject.cs#L284)):*
> ```Smalltalk
> 				return false;
> 			}
> 			var reader = XmlReader.Create(liftPath);
> ```

I believe that XmlReader implements IDisposable. If that is true, this should be wrapped in a using statement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/25)*

**Comment by glasseyes** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/WeSay.ConfigTool/ConfigurationWindow.cs, line 297 at r1](https://reviewable.io:443/reviews/sillsdev/wesay/25#-KynKOgBYfR0j6OvWKe1:-KynXBVhc444Ox95bK0Y:b-896fix) ([raw file](https://github.com/sillsdev/wesay/blob/8542e89e1691942b099eada25875c9c6404442e4/src/WeSay.ConfigTool/ConfigurationWindow.cs#L297)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I noticed that most of the calls to this method pass "false" to the "newClone" parameter. You might want to consider giving this parameter a default value of "false". It is entirely up to you though. I just wanted to make you aware of the option.
</blockquote></details>

Done.

---

*[src/WeSay.Project/WeSayWordsProject.cs, line 284 at r1](https://reviewable.io:443/reviews/sillsdev/wesay/25#-KynJweyw_wxMylkxgc-:-KynV2tZcy_W_LcsESLU:b-896fix) ([raw file](https://github.com/sillsdev/wesay/blob/8542e89e1691942b099eada25875c9c6404442e4/src/WeSay.Project/WeSayWordsProject.cs#L284)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I believe that XmlReader implements IDisposable. If that is true, this should be wrapped in a using statement.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/25)*

**Comment by megahirt** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r1, 3 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/WeSay.ConfigTool/ConfigurationWindow.cs, line 296 at r1](https://reviewable.io:443/reviews/sillsdev/wesay/25#-KynR17q20EdLus-AV9t:-KynR17q20EdLus-AV9u:bthjx0u) ([raw file](https://github.com/sillsdev/wesay/blob/8542e89e1691942b099eada25875c9c6404442e4/src/WeSay.ConfigTool/ConfigurationWindow.cs#L296)):*
> ```Smalltalk
> 		///
> 		/// </summary>
> 		/// <returns>true if the project was sucessfully opend</returns>
> ```

typo "opened"

---

*[src/WeSay.ConfigTool/ConfigurationWindow.cs, line 297 at r1](https://reviewable.io:443/reviews/sillsdev/wesay/25#-KynKOgBYfR0j6OvWKe1:-KynR6EP3PjadJ5TMI5x:bmwr29a) ([raw file](https://github.com/sillsdev/wesay/blob/8542e89e1691942b099eada25875c9c6404442e4/src/WeSay.ConfigTool/ConfigurationWindow.cs#L297)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I noticed that most of the calls to this method pass "false" to the "newClone" parameter. You might want to consider giving this parameter a default value of "false". It is entirely up to you though. I just wanted to make you aware of the option.
</blockquote></details>

I agree a default param would be nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/25#-:-KynXL0gzAffK2xn4Vfm:bnfp4nl)*

**Comment by glasseyes** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/WeSay.ConfigTool/ConfigurationWindow.cs, line 296 at r1](https://reviewable.io:443/reviews/sillsdev/wesay/25#-KynR17q20EdLus-AV9t:-KynXpIPv9RkUTUSI7x9:b-896fix) ([raw file](https://github.com/sillsdev/wesay/blob/8542e89e1691942b099eada25875c9c6404442e4/src/WeSay.ConfigTool/ConfigurationWindow.cs#L296)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

typo "opened"
</blockquote></details>

Done.

---

*[src/WeSay.ConfigTool/ConfigurationWindow.cs, line 297 at r1](https://reviewable.io:443/reviews/sillsdev/wesay/25#-KynKOgBYfR0j6OvWKe1:-KynXrQd3Udx4uXpiFR6:b9y489r) ([raw file](https://github.com/sillsdev/wesay/blob/8542e89e1691942b099eada25875c9c6404442e4/src/WeSay.ConfigTool/ConfigurationWindow.cs#L297)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

I agree a default param would be nice
</blockquote></details>

still Done ;).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/25)*

**Comment by ddaspit** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/25#-:-KytA1Fe9L9iM_qecNB1:bnfp4nl)*

**Pull request merged**
