### PR TITLE
Fix LT-18806:In WeSay, all PartsOfSpeech appear in English

### PR DESCRIPTION
**Pull request by vkarthim**
*Code added to set default WritingSystem

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/wesay/33)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
@vkarthim I think this commit isn't quite grabbing the default from the gloss field, I think it needs a bit more work.

**Comment by glasseyes** [comment]
That's the right kind of idea thanks. It should get the meaning field WS rather than hard coding the gloss field. I'll put a GetMeaningField into ViewTemplate so you can get it.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/33#-:-L4oGMtUiEgNlXZORxbC:b-ngctud)*

**Comment by glasseyes** [comment]
The PartsOfSpeech.xml defaults file has en, fr and es. So if the field is LexSense.WellKnownProperties.PartOfSpeech then it should either be one of those or user defined.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/33#-:-L4oK8Akt0rX4v19QEUi:bbmb05d)*

**Comment by glasseyes** [comment]
You will need to rebase against develop branch to get ViewTemplate.GetMeaningField

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/33#-:-L4oPKH_myxetV4uCeQ0:bfkgqk0)*

**Comment by vkarthim** [comment]
Thanks for your work, I made changes and submitted for code-review.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/33#-:-L4ptLLD4mDcrsgLaN5L:bbmk6zr)*

**Comment by glasseyes** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/33#-:-L4scoTsrmiJTlvIEBdQ:bnfp4nl)*

**Comment by glasseyes** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/33)*

**Pull request merged**
