### PR TITLE
Make WeSay work with software.sil.org/wesay

### PR DESCRIPTION
**Pull request by JohnThomson**
New web site being created for WeSay; new installers need to be put where it wants with the info it wants, and places where the program knows about the web site needed changing.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/wesay/8)

### CODE REVIEW

**Comment by JohnThomson** [comment]
I don't think this should be merged; it's just pushed for review.

**Comment by megahirt** [comment]
Should it eventually be merged?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/8#-:-Kim50TNMlyYOEWFfvhp:bjprbxy)*

**Comment by JohnThomson** [comment]
If (a) no one sees a problem with it, and (b) I can get WeSay to build so I can test it, and it works, then yes, it should be merged. It's not just a curiosity. I just meant that it probably shouldn't be automatically merged by the first person who doesn't see an obvious problem, because it's very tentative and quite untested.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/8#-:-KimrRRFSOUXbXezVJuZ:b-b5scpg)*

**Comment by megahirt** [comment]
It :lgtm: although I haven't built/tested it.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/8#-:-KinOs7NVufndPIg36J8:b-kkbcdd)*

**Pull request merged**
