### PR TITLE
Use nuget

### PR DESCRIPTION
**Pull request by madskinner**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/wesay/40)

### CODE REVIEW

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 10 of 73 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/wesay/40)* status: 10 of 73 files reviewed, 1 unresolved discussion (waiting on @madskinner)

___
*[common/WritingSystems/en.ldml, line 0 at r1](https://reviewable.io/reviews/sillsdev/wesay/40#-MVcgQeO8nghA3x74LzO:-MVcgQeO8nghA3x74LzP:b-n5l8e8) ([raw file](https://github.com/sillsdev/wesay/blob/3ad7bdc4e70bc3a00cb6460f578f8a4743a38272/common/WritingSystems/en.ldml#L0)):*
This file needs to be restored, it was probably renamed to bad due to a previous error.

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 34 of 73 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/wesay/40)* status: 44 of 73 files reviewed, 5 unresolved discussions (waiting on @madskinner)

___
*[src/Addin.Transform/app.config, line 44 at r1](https://reviewable.io/reviews/sillsdev/wesay/40#-MVrZMoB0kE0cXta8PEq:-MVrZMoB0kE0cXta8PEr:bj07q57) ([raw file](https://github.com/sillsdev/wesay/blob/3ad7bdc4e70bc3a00cb6460f578f8a4743a38272/src/Addin.Transform/app.config#L44)):*
> ```
>         <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-6.1.0.0" newVersion="6.1.0.0" />
> ```
So this might be a sign that Autofac 6.1 should be used throughout. Or else, this project might prove to have issues.
___
*[src/LexicalTools/AddPictures/AddPicturesControl.cs, line 35 at r1](https://reviewable.io/reviews/sillsdev/wesay/40#-MVrZrps9qr8jGkISXET:-MVrZrps9qr8jGkISXEU:b-l1vfni) ([raw file](https://github.com/sillsdev/wesay/blob/3ad7bdc4e70bc3a00cb6460f578f8a4743a38272/src/LexicalTools/AddPictures/AddPicturesControl.cs#L35)):*
> ```
> //				IEnumerable<object> results = collection.GetMatchingPictures(_searchWords.Text, out foundExactMatches);
> //				_thumbnailViewer.LoadItems(collection.GetPathsFromResults(results, true));
> ```
I think it is safe to remove the old code.
___
*[src/LexicalTools/AddPictures/AddPicturesTask.cs, line 35 at r1](https://reviewable.io/reviews/sillsdev/wesay/40#-MVr_62d3zGsLkGmyEjk:-MVr_62d3zGsLkGmyEjl:byaobun) ([raw file](https://github.com/sillsdev/wesay/blob/3ad7bdc4e70bc3a00cb6460f578f8a4743a38272/src/LexicalTools/AddPictures/AddPicturesTask.cs#L35)):*
> ```
> 			//ArtOReadingImageCollection
> 			//_imageCollection = ArtOReadingImageCollection.FromStandardLocations();
> ```
Probably should remove this.
___
*[src/LexicalTools/AddPictures/AddPicturesTask.cs, line 36 at r1](https://reviewable.io/reviews/sillsdev/wesay/40#-MVr_95FBIqzTu1kIgz1:-MVr_95FBIqzTu1kIgz2:b1r2cy2) ([raw file](https://github.com/sillsdev/wesay/blob/3ad7bdc4e70bc3a00cb6460f578f8a4743a38272/src/LexicalTools/AddPictures/AddPicturesTask.cs#L36)):*
> ```
> "%ProgramData%\\SIL\\ImageCollections\\Art Of Reading"
> ```
I'm surprised there isn't a pubic constant for this location.
___
*[src/LexicalTools.Tests/LexicalTools.Tests.csproj, line 92 at r1](https://reviewable.io/reviews/sillsdev/wesay/40#-MVr_PYm-IzMZOz27Ozs:-MVr_PYnEtyfgELa3Dxt:b-tqzznt) ([raw file](https://github.com/sillsdev/wesay/blob/9a33635898918084188f2a1bdd1624951baafd02/src/LexicalTools.Tests/LexicalTools.Tests.csproj#L92)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> 
>     </Reference>
>     <Reference Include="SIL.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=cab3c8c5232dfcf2">
>       <HintPath>..\..\lib\Debug\SIL.Core.dll</HintPath>
>     </Reference>
>     <Reference Include="SIL.DictionaryServices, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
>       <SpecificVersion>False</SpecificVersion>
>       <HintPath>..\..\lib\$(Configuration)\SIL.DictionaryServices.dll</HintPath>
>     </Reference>
>     <Reference Include="SIL.Lift, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
>       <SpecificVersion>False</SpecificVersion>
>       <HintPath>..\..\lib\$(Configuration)\SIL.Lift.dll</HintPath>
>     </Reference>
>     <Reference Include="SIL.TestUtilities, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
> ```
</details>

This is a lot of references removed. It is possible that they weren't needed. If the tests in this project pass, then this is a  very nice bit of house keeping.
___
*[src/Lift2WeSay/SampleDataProcessor.csproj, line 72 at r1](https://reviewable.io/reviews/sillsdev/wesay/40#-MVr_oggE_vFZWe1Ss5O:-MVr_oggE_vFZWe1Ss5P:bnjeeor) ([raw file](https://github.com/sillsdev/wesay/blob/3ad7bdc4e70bc3a00cb6460f578f8a4743a38272/src/Lift2WeSay/SampleDataProcessor.csproj#L72)):*
> ```
> .\..\..\..\..\..\
> ```
At first glance this seems like too many directories to back out. Maybe verify this is correct.
___
*[src/WeSay.AddinLib/WeSay.AddinLib.csproj, line 79 at r1](https://reviewable.io/reviews/sillsdev/wesay/40#-MVraCDCCz6HU3u7mzog:-MVraCDCCz6HU3u7mzoh:b-38yujy) ([raw file](https://github.com/sillsdev/wesay/blob/3ad7bdc4e70bc3a00cb6460f578f8a4743a38272/src/WeSay.AddinLib/WeSay.AddinLib.csproj#L79)):*
> ```
> ..\..\..\..\..\..\
> ```
Again, if it was only in ..\..\lib before, backing out 4 more directories seems suspicious
___
*[src/WeSay.App/TabbedForm.cs, line 6 at r1](https://reviewable.io/reviews/sillsdev/wesay/40#-MVradAiDCQ1kTniEyn_:-MVradAiDCQ1kTniEyna:b-rsn2m1) ([raw file](https://github.com/sillsdev/wesay/blob/3ad7bdc4e70bc3a00cb6460f578f8a4743a38272/src/WeSay.App/TabbedForm.cs#L6)):*
> ```
> //using System.IO;
> //using System.Linq;
> //using System.Reflection;
> ```
Delete
___
*[src/WeSay.App/WeSay.App.csproj, line 130 at r1](https://reviewable.io/reviews/sillsdev/wesay/40#-MVranAg1UwgLL_lGDnn:-MVranAhD7zaik2tp59Z:b7sdggf) ([raw file](https://github.com/sillsdev/wesay/blob/3ad7bdc4e70bc3a00cb6460f578f8a4743a38272/src/WeSay.App/WeSay.App.csproj#L130)):*
> ```
> ..\..\..\..\..\..\.
> ```
ditto

**Comment by madskinner** [comment]
..\..\..\..\..\..\ comes about because the nuget packages have been installed by default into my user directory. Where would you expect them to be installed?
No reference anywhere to 'Art of Reading' except in a control description, presumably for a tooltip. Where would you expect to find public constants declared?
the //old code removed
All Autofac references set to autofac6.1.0/lib/netstandard2.0

**Comment by jasonleenaylor** [comment]
@madskinner I see. The problem is that the users directory may not be in the same relative directory for every setup. I think we'll need to reference them from the Output directory. Visual Studio will do the copy. Once you have everything using the Nuget packages the output folder should be safe.

**Comment by jasonleenaylor** [comment]
Also, FYI you don't need to close a PR just because you have changes. You can make more commits to the branch and push it and the contents will update here.

**Pull request closed without merging**
