### PR TITLE
Run installer

### PR DESCRIPTION
**Pull request by josephmyers**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/wesay/104)

### CODE REVIEW

**Comment by josephmyers** [comment]
The installer is building and appears to install, but neither software launches.

**Comment by josephmyers** [comment]
I'm still looking into where/how build artifacts get uploaded with this GHA, but the installer itself is ready for testing.

**Comment by josephmyers** [comment]
https://github.com/sillsdev/wesay/actions/runs/10612871182

This is the most recent Installer CI run, before I restored the original GHA run settings. The artifacts are at the bottom of the page.

**Review by megahirt — APPROVED** [review]
Code changes look good to me!  I will test out the installer now

**Comment by megahirt** [comment]
Installer works, so we can merge this!

**Pull request merged**
