### PR TITLE
Bugfix/cross reference export

### PR DESCRIPTION
**Pull request by glasseyes**
no WeSayConfig change now

If the CrossReference field is enabled in a project then when you do SFM export then it will mark all the entries that have cross reference relations as dirty and save them - this will normalise the cross-references and it will also normalise the Word in that entry if it hasn't been already.

Now includes a test

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/wesay/24)

### CODE REVIEW

**Comment by glasseyes** [comment]
@megahirt review assigned to you as you are the one with the support email to see what is wanted, assign to someone else if you think they should do it

**Comment by megahirt** [comment]
Hi Daniel, per our discussion we won't need to keep track of the variable touchAllEntriesCompleted but instead will run the code block on every open of the WeSay config tool.  The "read/write" every entry will only happen if cross references are enabled on the project.  The read/write step is a fast operation and not expected to have any performance impact on the average-sized project.

The migrate9to10.xsl is no longer necessary as far as I can tell.  Thanks.

---

Reviewed 8 of 10 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/24#-:-KynbwXk6tXL8JeGYUm8:b-ktgm8j)*

**Comment by megahirt** [comment]
Still further discussion we've acknowledged that there is no need to do the read/write all entries except on SFM export, which is where I believe this functionality will be in a new PR.  Is that correct @glasseyes ?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/24#-:-KzRyjEBJlRsdDOz4dSJ:b-o7y3vg)*

**Comment by glasseyes** [comment]
it will be an update of this PR, sorry I hadn't meant this one for review

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/24#-:-KzSMPX4qjiN9jLsj-1v:b-tp4x8q)*

**Comment by megahirt** [comment]
ok, will wait for an update

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/24#-:-KzagjaUm8IiFeMQ3dwV:b-3ledl9)*

**Comment by megahirt** [comment]
A few comments.  Code looks good in general.  I am hoping for more comment prose explaining the regex and the why the methods are necessary and what they accomplish.  Basically, the stuff we've already talked about but that a brand new WeSay dev would be able to read and understand.  Thanks!

---

Reviewed 6 of 13 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Addin.Transform/SfmTransformer.cs, line 173 at r3](https://reviewable.io:443/reviews/sillsdev/wesay/24#-L-VXtLD6OoKxtM5FjyZ:-L-VXtLD6OoKxtM5Fjy_:b4xv34s) ([raw file](https://github.com/sillsdev/wesay/blob/f586b4a0178f20c2b9920646ec11f03d1532f5a8/src/Addin.Transform/SfmTransformer.cs#L173)):*
> ```Smalltalk
> 
> 			// check that sfm file has no problem references
> 			bool has_problems = Palaso.IO.FileUtils.GrepFile(output, @"\\lf\ confer\ =\ (.+)_([0-9a-f\-]+)");
> ```

We need a more specific comment stating exactly what this regex does / is looking for.  I can't read it / understand it.  This would help to clarify "problem references" which it's not clear what the means from the code.  "problem references" implies that the TransformLiftToText() method above might produce bad data, which is confusing.  I know this is technically correct, but we need to have more documentation in the code to explain why we have to cleanup after our own code :)  It's good form to reference a JIRA in the code as supplemental documentation of the code's explanation.  This could be one of those cases where the comments are longer than the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/24#-:-L-VZTavkFB4CcTU6Lmj:b-gr2kn9)*

**Comment by glasseyes** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Addin.Transform/SfmTransformer.cs, line 173 at r3](https://reviewable.io:443/reviews/sillsdev/wesay/24#-L-VXtLD6OoKxtM5FjyZ:-L-VhgpiGSZp1kz6BMdA:b-896fix) ([raw file](https://github.com/sillsdev/wesay/blob/f586b4a0178f20c2b9920646ec11f03d1532f5a8/src/Addin.Transform/SfmTransformer.cs#L173)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

We need a more specific comment stating exactly what this regex does / is looking for.  I can't read it / understand it.  This would help to clarify "problem references" which it's not clear what the means from the code.  "problem references" implies that the TransformLiftToText() method above might produce bad data, which is confusing.  I know this is technically correct, but we need to have more documentation in the code to explain why we have to cleanup after our own code :)  It's good form to reference a JIRA in the code as supplemental documentation of the code's explanation.  This could be one of those cases where the comments are longer than the code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/24)*

**Comment by megahirt** [comment]
This is better.  Thank you.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/wesay/24#-:-L-Vm5xJGMukXUDlpmxu:b-rxrohi)*

**Pull request merged**
