### PR TITLE
Update LocalizedLists-ar.xml (2019-05-23)

### PR DESCRIPTION
**Pull request by papeh**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/wesay/39)

### CODE REVIEW

**Comment by papeh** [comment]
@andrew-polk, do you know who's maintaining this repo?

**Comment by andrew-polk** [comment]
My understanding is that wesay is officially no longer supported.

**Review by papeh — COMMENTED** [review]
right. But could we merge this PR so that these updates are available if we ever get back to it?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/wesay/39#-:-MQJbqxH64OgthrABzJI:bi98w1x)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by andrew-polk** [comment]
I can't even review it without downloading the repo. Does it really need review?

**Comment by papeh** [comment]
Not really, but I don't have write access to this repository. Could you merge it for me or grant me access?

**Pull request merged**
